export default [
    {
      id: "#123",
      avatar: "1.jpg",
      userinfo: "Hanna Gover",
      usermail: "hgover@gmail.com",
      phone: "+123 456 789",
      jdate: "12-10-2014",
      role: "Designer",
      rolestatus: "cyan lighten-3",
    },
    {
      id: "#452",
      avatar: "2.jpg",
      userinfo: "Daniel Kristeen",
      usermail: "hgover@gmail.com",
      phone: "+234 456 789",
      jdate: "10-09-2014",
      role: "Developer",
      rolestatus: "light-blue lighten-3",
    },
    {
      id: "#565",
      avatar: "3.jpg",
      userinfo: "Julian Josephs",
      usermail: "hgover@gmail.com",
      phone: "+345 456 789",
      jdate: "01-10-2013",
      role: "Accountant",
      rolestatus: "teal lighten-3",
    },
    {
      id: "#785",
      avatar: "4.jpg",
      userinfo: "Jan Petrovic",
      usermail: "hgover@gmail.com",
      phone: "+456 456 789",
      jdate: "02-10-2017",
      role: "Designer",
      rolestatus: "green lighten-3",
    },
    {
      id: "#564",
      avatar: "5.jpg",
      userinfo: "Leanne Graham",
      usermail: "hgover@gmail.com",
      phone: "+567 456 789",
      jdate: "10-9-2015",
      role: "HR",
      rolestatus: "deep-purple lighten-2",
    },
    {
      id: "#980",
      avatar: "6.jpg",
      userinfo: "Mrs. Dennis Schulist",
      usermail: "hgover@gmail.com",
      phone: "+678 456 789",
      jdate: "10-5-2013",
      role: "Designer",
      rolestatus: "indigo lighten-2",
    },
    {
      id: "#521",
      avatar: "7.jpg",
      userinfo: "Kurtis Weissnat",
      usermail: "hgover@gmail.com",
      phone: "+123 456 789",
      jdate: "05-10-2012",
      role: "Manager",
      rolestatus: "blue lighten-2",
    },
    {
      id: "#450",
      avatar: "8.jpg",
      userinfo: "Nicholas Runolfsdottir V",
      usermail: "hgover@gmail.com",
      phone: "+234 456 789",
      jdate: "11-10-2014",
      role: "Chairman",
      rolestatus: "red lighten-3",
    },
    {
      id: "#212",
      avatar: "2.jpg",
      userinfo: "Glenna Reichert",
      usermail: "hgover@gmail.com",
      phone: "+345 456 789",
      jdate: "12-5-2017",
      role: "Designer",
      rolestatus: "indigo lighten-4",
    },
    {
      id: "#152",
      avatar: "1.jpg",
      userinfo: "Clementina DuBuque",
      usermail: "hgover@gmail.com",
      phone: "+456 456 789",
      jdate: "18-5-2009",
      role: "Developer",
      rolestatus: "indigo lighten-4",
    },
  ];
  