name: "\U0001F41B 错误回报 Bug Report"
title: "\U0001F41B [Bug]: "
description: 回报错误以便我们修复它 Create a bug report to help us fix it.
labels: ["state:pending", "type:bug"]

body:
  - type: markdown
    id: notice
    attributes:
      value: |
        ### 注意事项
        **此代码库与外部或使用到的第三方模块无关，应该到他们的代码库提交错误回报，如果您认为与本项目有关，请在此提交错误回报**
        - 如果你只是要询问问题，可以透过 SeeDAO [Discord 服务器](https://discord.gg/seedao) 询问
        - 如果你希望直接给予改善的建议, 请切换另一个模版 **🚀 Feature Request** 提交问题
        - 请尽量提供更多信息作为参考，不用怕过长或无关紧要，这样能减少来回沟通时间
        ### Notice
        **This repository is not related to external or third-part OS modules. If you have a problem with them, open an issue under their repos. If you think the problem is related to OS, open the issue here.**
        - Don't forget you can ask your questions in our [Discord server](https://discord.gg/seedao).
        - If you have a suggestion for a feature you would like to see, open the issue with the **✏️ Feature Request** template.
        - If you are unfamiliar with chinese, please write your issue with clear and understandable English.
  - type: textarea
    id: description
    attributes:
      label: "错误描述 Bug Description"
      description: "清楚详细地描述是什么错误 A clear and detailed description of what the bug is."
      placeholder: "清楚详细地解释你的问题 Explain your problem clearly and in detail."
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 如何重现错误 How to Reproduce
      description: "重现该行为的步骤，以及最终要看到的结果 Steps to reproduce the behavior and what should be observed in the end."
      placeholder: "逐步告诉我们如何重现您的问题，以及我们最终应该看到什么 Tell us step by step how we can replicate your problem and what we should see in the end."
      value: |
          重现错误的步骤为:
          1. 到 '....'
          2. 点击 '....'
          3. 输入 '....'
          4. 就会看到 '....'
          Steps to reproduce the behavior:
          1. Go to '....'
          2. Click on '....'
          3. Do '....'
          4. See '....'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为 Expected Behavior
      description: "清晰详细地描述您认为应该有的结果 A clear and detailed description of what you think should happen."
      placeholder: "告诉我们你预期应该得到什么 Tell us what OS should normally do."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "代码版本 OS Version"
      description: "一些错误可能会在未来的版本中得到修复，因此我们必须知道您的版本 Some bugs may be fixed in future OS releases, so we have to know your OS version."
      placeholder: "写下你的代码版本 Write your OS version. (v2.33.0, v2.34.1...)"
    validations:
      required: true
  - type: textarea
    id: snippet
    attributes:
      label: "代码片段 (选填) Code Snippet (optional)"
      description: "对于某些问题，我们需要了解您部份代码 For some issues, we need to know some parts of your code."
      placeholder: "分享您认为与问题相关的代码片段 Share a code snippet that you think is related to the issue."
      render: typescript
      value: |
       function func(a: number, b: number){
        return a+b
       }
  - type: checkboxes
    id: terms
    attributes:
      label: "检查清单 Checklist:"
      description: "提交之前请确认以下事项 By submitting this issue, you confirm that:"
      options:
        - label: "我同意社区行为准则 I agree to follow SeeDAO's [Code of Conduct](https://github.com/seedao-opensource/os-frontend-ce/blob/master/.github/CODE_OF_CONDUCT.md)."
          required: true
        - label: "我已经检查没有重复或类似的议题 I have checked for existing issues that describe my suggestion prior to opening this one."
          required: true
        - label: "我了解没有依照格式提交错误回报，将会被关闭 I understand that improperly formatted bug report may be closed without explanation."
          required: true